name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: |
          docker-compose build postgres
          docker-compose build gateway_service
          docker-compose build reservation_service
          docker-compose build payment_service
          docker-compose build loyalty_service
      - name: Setup db
        run: |
          docker-compose up -d postgres
          docker-compose logs postgres
          sleep 5
          cd postgres
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < scripts/db-v2.sql
          cd ..
          cd hotels_booking_system/scripts_db
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < create_tables.sql
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < fill_cars_table.sql
          cd ..

      - name: Run containers
        timeout-minutes: 10
        run: |
          docker-compose up -d reservation_service
          docker-compose up -d payment_service
          docker-compose up -d loyalty_service
          docker-compose up -d gateway_service

          docker-compose logs reservation_service
          docker-compose logs payment_service
          docker-compose logs loyalty_service
          docker-compose logs gateway_service
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Wait 15s
        uses: jakejarvis/wait-action@master
        with:
            time: '15s'

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

#      - uses: education/autograding@v1
#        id: autograder
#        continue-on-error: true
#
#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 2
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v